title: EXTRA 2019-2
author: Mr. Author
email: mymail@do.ma.in
description: > # this means to ignore newlines until "show_excerpts:"
  (V014 20200112) Operating Systems EXTRA 2019-2.
  Operating Systems EXTRA 2019 2

show_excerpts: false # set to true to show excerpts on the homepage

exclude:
  - SandBox/

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
xtheme:
  date_format: "%b %-d, %Y"

  social_links:
    github:  webjekyll
  # generate social links in footer
    # twitter: jekyllrb
    # rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
