#!/bin/bash
IFS=$'\n'  	
for line in $(cat $1); do
	username=`(echo $line | awk '{print $1}')`
	password=`(echo $line | awk '{print $2}')`
	sudo useradd $username
	sudo usermod -d /home/$username
	sudo echo $password | passwd --stdin $1
done
unset IFS
