#!/bin/bash
input="./users.txt"
while IFS= read -r line;do
	fields=($(printf "%s" "$line"|cut -d',' --output-delimiter=' ' -f1-))
	useradd "${fields[0]}" 
	echo "user $line added successfully!"
	"${fields[1]}" | chpasswd 
	echo "Password for user $line changed successfully"
done < "$input"
