#!/bin/bash
# Usage: password generator from username input
# Author: Selvy Fitriani
# References : 
# 1. https://gist.github.com/earthgecko/3089509
# 2. https://www.cyberciti.biz/faq/bash-while-loop/
# 3. https://linuxize.com/post/bash-append-to-file/
#!/usr/bin/env sh
echo 'Generating 12-character passwords'
var=$1
var2=$2
rm -fi $var2
mkdir -p ~/generatePasswordsTemp
touch ~/generatePasswordsTemp/passwords.txt
while read -r user; do
dd if=/dev/urandom count=1 2> /dev/null | uuencode -m - | sed -ne 2p | cut -c-8 >> ~/generatePasswordsTemp/passwords.txt; done < $var

echo |paste $var passwords.txt > $var2

rm -f ~/generatePasswordsTemp/passwords.txt
	