#!/bin/bash
# Usage: password generator from username input
# Author: Selvy Fitriani
# References : 
# 1. https://gist.github.com/earthgecko/3089509
# 2. https://www.cyberciti.biz/faq/bash-while-loop/
# 3. https://linuxize.com/post/bash-append-to-file/
var=$1
rm users.txt
while read -r user; do 
cat /dev/urandom | tr -dc "a-zA-Z0-9\n" | fold -w 8 | head -n 1 >> passwords.txt; done < $var

echo |paste $var passwords.txt > users.txt

rm passwords.txt