#!/bin/bash

:'
  Copyright (C) 2020-2020 Sayid Abyan Rizal Shiddiq
  This program is free script/software. This program is distributed in the 
  hope that it will be useful, but WITHOUT ANY WARRANTY; without even the 
  implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
'

IFS=$'\n'  	
for line in $(cat $1); do
	username=`(echo $line | awk '{print $1}')`
	password=`(echo $line | awk '{print $2}')`
	adduser --disabled-password --gecos "" $username
	echo $username:$password | chpasswd
done
unset IFS
