#!/bin/bash

:'
  Copyright (C) 2020-2020 Sayid Abyan Rizal Shiddiq
  This program is free script/software. This program is distributed in the 
  hope that it will be useful, but WITHOUT ANY WARRANTY; without even the 
  implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
'

sudo yes | cp -rf ./upgrade /usr/local/bin/upgrade;
sudo chmod +x /usr/local/bin/upgrade
sudo upgrade;

sudo systemctl enable ssh;
sudo systemctl start ssh;

sudo apt install hostapd -y;
sudo apt install dnsmasq -y;

sudo yes | cp -rf ./dhcpcd.conf /etc/dhcpcd.conf;

sudo mv /etc/dnsmasq.conf /etc/dnsmasq.conf.orig;

sudo yes | cp -rf ./dnsmasq.conf /etc/dnsmasq.conf;

sudo yes | cp -rf ./hostapd.conf /etc/hostapd/hostapd.conf;

sudo yes | cp -rf ./hostapd /etc/default/hostapd;

sudo yes | cp -rf ./rc.local /etc/rc.local;

sudo yes | cp -rf ./wpa_supplicant.conf /etc/wpa_supplicant/wpa_supplicant.conf

sudo systemctl stop hostapd;
sudo systemctl stop dnsmasq;
sudo systemctl stop dhcpcd;
sudo systemctl disable hostapd;
sudo systemctl disable dnsmasq;
sudo systemctl disable dhcpcd;

sudo yes | cp -rf ./wifistart /usr/local/bin/wifistart;
sudo chmod +x /usr/local/bin/wifistart;
sudo reboot;