#!/bin/bash

:'
  Copyright (C) 2020-2020 Sayid Abyan Rizal Shiddiq
  This program is free script/software. This program is distributed in the 
  hope that it will be useful, but WITHOUT ANY WARRANTY; without even the 
  implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
'

sudo apt update;
sudo apt upgrade -y;
sudo apt autoremove --purge -y;
sudo apt autoclean -y;
sudo apt clean -y;
