#!/usr/bin/env bash
sudo apt-get update;
sudo apt-get upgrade -y;
sudo apt-get autoremove --purge -y;
sudo apt-get autoclean -y;
sudo apt-get clean -y;

sudo apt-get install hostapd dnsmasq;

echo 'interface uap0\n\tstatic ip_address=192.168.50.1/24\n\tnohook wpa_supplicant' > /etc/dhcpcd.conf;

sudo mv /etc/dnsmasq.conf /etc/dnsmasq.conf.orig;

echo 'interface=lo,uap0\nbind-interfaces\nserver=8.8.8.8\ndomain-needed\nbogus-priv\ndhcp-range=192.168.1.2,192.168.1.99,12h' > /etc/dnsmasq.conf;

echo 'channel=1\n\nssid=yourSSIDhere\nwpa_passphrase=extra192\ninterface=uap0\nhw_mode=g\nmacaddr_acl=0\nauth_algs=1\nignore_broadcast_ssid=0\nwpa=2\nwpa_key_mgmt=WPA-PSK\nwpa_pairwise=TKIP\nrsn_pairwise=CCMP\ndriver=nl80211' > /etc/hostapd/hostapd.conf;

path='/etc/hostapd/hostapd.conf';
sed -i "s/^DAEMON_CONF=.*/DAEMON_CONF=${path}/" /etc/default/hostapd;

echo '#!/bin/bash\n\necho "Stopping network services (if running)..."\nsystemctl stop hostapd.service\nsystemctl stop dnsmasq.service\nsystemctl stop dhcpcd.service\n\necho "Removing uap0 interface..."\niw dev uap0 del\n\necho "Adding uap0 interface..."\niw dev wlan0 interface add uap0 type __ap\n\necho "IPV4 forwarding: setting..."\nsysctl net.ipv4.ip_forward=1\necho "Editing IP tables..."\niptables -t nat -A POSTROUTING -s 192.168.70.0/24 ! -d 192.168.70.0/24 -j MASQUERADE\n\nifconfig uap0 up\n\necho "Starting hostapd service..."\nsystemctl start hostapd.service\nsleep 10\n\necho "Starting dhcpcd service..."\nsystemctl start dhcpcd.service\nsleep 5\n\necho "Starting dnsmasq service..."\nsystemctl start dnsmasq.service\necho "wifistart DONE"' > /usr/local/bin/wifistart;

sudo systemctl stop hostapd;
sudo systemctl stop dnsmasq;
sudo systemctl stop dhcpcd;
sudo systemctl disable hostapd;
sudo systemctl disable dnsmasq;
sudo systemctl disable dhcpcd;

sudo reboot;
